version: '3.8'

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cmp
      - MYSQL_ROOT_PASSWORD=dipro0243
   
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "3400:80"
    depends_on:
      - db
    

  app:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www
    ports:
      - "9000:9000"
    
